# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Releases my app to the appstore."
  lane :release_app do
    export_app
    upload_app
  end

  desc "To export my app."
  lane :export_app do
    gym(
      project: "11MDivisionsList.xcodeproj",
      scheme: "11MDivisionList",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "ReleaseApp.ipa"
    )
  end  

  desc "To deliver my app."
  lane :upload_app do
    deliver(
      ipa: "ReleaseApp.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true,
      force: true,
      precheck_default_rule_level: :error
    )
  end
end



